# Generated by Django 2.2.16 on 2020-09-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuelength', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='updatetime',
            field=models.DateTimeField(null=True),
        ),
    ]
