# Generated by Django 2.2.16 on 2020-09-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuelength', '0002_queue_updatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='store_queue',
            fields=[
                ('store_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('queue_id', models.CharField(max_length=255)),
                ('length', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='queue',
        ),
    ]
